// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicHomepage,
  DefaultHomepageProps
} from "./plasmic/app_starter/PlasmicHomepage";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

export interface HomepageProps extends DefaultHomepageProps {}

function Homepage_(props: HomepageProps, ref: HTMLElementRefOf<"div">) {
  const dishFromRef = React.useRef();
  return (
  <PlasmicHomepage
    dishForm={{
      ref: dishFromRef,
      onSubmit: (data: any) => {
        console.log({data})
      }
    }}
    root={{ ref }} {...props} 
    />
  );
}

const Homepage = React.forwardRef(Homepage_);
export default Homepage;
